services:
  - type: web
    name: smartestoque
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.2
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN2_EMAIL
        sync: false
      - key: ADMIN2_PASSWORD
        sync: false
      - key: ADMIN2_NAME
        sync: false
